### ISSUE TITLE
Can't get opal to work

### ISSUE THREAD

**Issue by stugol** [opal/opal#1396] opened 2016-03-15 23:27 UTC
I'm unable to get Opal to work in Sinatra.

My HAML filter:

```rb
module Haml::Filters::Opal
  include Haml::Filters::Base

  def render_with_options ruby, options
    text = ::Opal.compile(ruby)
    type = (options[:format] == :html5) ? '' : " type=#{options[:attr_wrapper]}text/javascript#{options[:attr_wrapper]}"

    text.rstrip!
    text.gsub!("\n", "\n    ")

    <<HTML
<script#{type}>
  //<![CDATA[
    #{text}
  //]]>
</script>
HTML
  end
end
```
In my HAML:
```haml
:opal
	require 'opal-jquery'
	alert "OPAL"
```
I get: `undefined method 'alert' for main`

**Comment by elia** [comment] 2016-03-16 11:40
@stugol the problem is that you're using `::Opal.compile(ruby)` directly, instead you should use `Opal::Builder`:


```rb
builder = Opal::Builder.new
builder.build_str(ruby, options.filename) # or options[:filename], don't know the internals
text = builder.to_s
```

docs for `#build_str`: http://opalrb.org/docs/api/v0.9.2/lib/Opal/Builder.html#build_str-instance_method

**Comment by stugol** [comment] 2016-03-17 03:51
Thanks for the help. I'm now getting `Permission denied @ rb_sysopen - /var/lib/gems/2.1.0/gems/paggio-0.2.6/lib/paggio.rb` but at least it's progress ;)

The permissions on that file are `-rw-------`, which would explain the problem. But I installed `paggio` using `sudo gem` as per usual; so why am I getting this error when presumably most people do not?

**Comment by stugol** [comment] 2016-03-17 03:56
Also, if I adjust the permissions for all the `paggio` files, I get this error:
```
TypeError: undefined is not an object (evaluating '$kwargs.$$smap')
(anonymous function)invoicing:1051
(anonymous function)invoicing:5330
(anonymous function)invoicing:5333
(anonymous function)invoicing:5334
(anonymous function)invoicing:5335
loadopal.min.js:1:21215
requireopal.min.js:1:21601
(anonymous function)invoicing:8676
loadopal.min.js:1:21215
requireopal.min.js:1:21601
(anonymous function)invoicing:12999
loadopal.min.js:1:21215
requireopal.min.js:1:21601
(anonymous function)invoicing:13012
(anonymous function)invoicing:13014
```

My haml-embedded code:
```
:opal
	require 'browser'
	alert "OPAL"
```

**Comment by KenStipek** [comment] 2016-03-22 23:07
I don't believe `alert` is part of opal. [Check this out from the Sinatra](https://github.com/opal/opal/blob/2e125c868e0b944658b74903c535932c9c4e989c/examples/sinatra/app/application.rb) example.

You should be able to do this as well:
```
:opal
    require 'opal-jquery'
    `alert("OPAL")`
```

**Comment by stugol** [comment] 2016-03-23 00:53
@KenStipek You're right, kinda. `alert` isn't part of Opal, but it _is_ part of `opal-jquery`, so in your example the backticks are redundant.

Except that Opal flatly refuses to `require 'opal-jquery`:
```
Opal::Builder::MissingRequire at /invoicing
A file required by "/mnt/data/Documents/Programming/ruby/intranet/views/pages/2.invoicing.haml" wasn't found. can't find file: "opal-jquery" in ["/var/lib/gems/2.1.0/gems/opal-0.9.2/opal", "/var/lib/gems/2.1.0/gems/opal-0.9.2/stdlib", "/var/lib/gems/2.1.0/gems/opal-0.9.2/lib", "/var/lib/gems/2.1.0/gems/opal-browser-0.2.0/opal", "/var/lib/gems/2.1.0/gems/paggio-0.2.6/lib"]
```

The gem exists, however:
```
$ pry
[1] pry(main)> require 'opal-jquery'
=> true
```
Why can't Opal find the gem?

**Comment by ylluminarious** [comment] 2016-03-23 12:57
@stugol Where is `opal-jquery` located? Being able to require it in pry or irb doesn't necessarily mean that the same thing should work everywhere; pry / irb may simply have the path that contains opal-jquery, whereas your application may not.

**Comment by stugol** [comment] 2016-03-24 09:11
It's located in the usual place: `/var/lib/gems/2.1.0/gems/opal-jquery-0.4.1/lib/opal-jquery.rb`

Why Opal isn't looking there is a mystery.

**Comment by elia** [comment] 2016-03-24 09:24
@stugol can you provide the compiled code (in a gist) and also the value of `Opal.paths` should help. 
Anyway in order to require from opal you need to add the lookup paths to `Opal.paths`, which is usually done by gems like `opal-jquery` when they are loaded on the CRuby side: https://github.com/opal/opal-jquery/blob/e64b70898c82096276331bdb2ab3e5ef8d1f2384/lib/opal/jquery.rb#L9-L12

**Comment by stugol** [comment] 2016-03-24 11:39
@elia Ah, I see. I have to `require` it both at the client-side and the server-side. It's working now, thanks.

Do you still want the compiled code? I have no idea how to get it. Also it's working, so... ;)

So I can't use normal gems on the client side, I suppose? Only gems designed specifically for this purpose?

What happens if I call things like `Kernel#exec` on the client side?

**Comment by stugol** [comment] 2016-03-24 11:40
Also, can I instruct `Opal::Builder` to _not_ wrap the resulting code in an anonymous function?

**Comment by elia** [comment] 2016-03-24 11:43
Great!

> Do you still want the compiled code? I have no idea how to get it. Also it's working, so... ;)

No, that was just to help debugging :)

> So I can't use normal gems on the client side, I suppose? Only gems designed specifically for this purpose?
Those designed to work with opal are more likely to work with it out of the box, for other gems you can try `Opal.use_gem`

> What happens if I call things like Kernel#exec on the client side?

You'll get a no method error ;)

> Also, can I instruct Opal::Builder to not wrap the resulting code in an anonymous function?

there's a compiler flag named `requireable` to control that (check the spelling on the api docs, i get it wrong all the time)

**Comment by elia** [comment] 2016-04-01 21:06
Closing, let me know if further help is needed, or even better ask for help on https://gitter.im/opal/opal :)

**Closed by elia** 2016-04-01 21:06 UTC
