### ISSUE TITLE
'?=' failed to parse

### ISSUE THREAD

**Issue by zetachang** [opal/opal#1076] opened 2015-08-26 05:13 UTC
Below script failed to parse.  #1074 might be related. And its around line https://github.com/opal/opal/blob/master/lib/opal/parser/lexer.rb#L1155

```ruby
?=
```
I am using v0.8.0.

How about change StringScanner implementation to,

```ruby
  def anchor(pattern)
    `new RegExp('^(?:' + pattern.toString().substr(1, pattern.toString().length - 2) + ')')`
  end
```

which will force to match from beginning even the provided pattern use alternation.

**Comment by alexdowad** [comment] 2015-12-08 22:27
Oooh... just noticed that you had suggested the same fix for #1074 which I also just used...

**Comment by alexdowad** [comment] 2015-12-08 22:28
`?=` parses just fine for me, even on v0.8.0.

**Comment by elia** [comment] 2015-12-09 08:38
Maybe it's a js only issue, I'm afk but

    opal -ropal-parser -e "p Opal::Parser.new 'a ?= b'"

could be showing that behavior

**Comment by alexdowad** [comment] 2015-12-09 08:52
`a ?= b` is not Ruby. `?=` is. It's a single-character string literal.

**Comment by elia** [comment] 2015-12-09 09:14
:confounded: sorry, I wondered while typing out… please keep the good part which is the way to reproduce within the compiled-to-JS version of the parser :)

**Comment by elia** [comment] 2015-12-09 09:24
Ok, can't reproduce either:

```
opal:master ⤑ be bin/opal -ropal-parser -e "p Opal::Parser.new.parse('p ?=')"
("call", nil, "p", ("argils", ("str", "=")))
opal:master ⤑ g cd 0-8-stable
opal:0-8-stable ⤑ be bin/opal -ropal-parser -e "p Opal::Parser.new.parse('p ?=')"
("call", nil, "p", ("arglist", ("str", "=")))
```

Closing, @zetachang feel free to reopen if you find a way to reproduce.

**Closed by elia** 2015-12-09 09:24 UTC
