### ISSUE TITLE
Class#name shows superclass as namespace on assignment

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1266] opened 2015-12-30 20:16 UTC
Given the following code:

```ruby
require 'opal'
Foo = Class.new
Bar = Class.new(Foo)

bar = Bar.new
puts bar.class.name
```

We would expect to see "Bar" in the console, but we instead see "Foo::Bar". I confirmed this does not happen when declaring the class using `class Foo < Bar`, though.

I only noticed this because I assign subclasses like this for [`GrandCentral` actions](https://github.com/clearwater-rb/grand_central#actions):

```ruby
module Actions
  TodosAction = GrandCentral::Action.create # Superclass for operations on the collection of todos
  AddTodo = TodosAction.with_attributes(:todo) # Subclass for a particular operation on the collection
end
```

When printing out the action history, I noticed `GrandCentral::Action::TodosAction::AddTodo` instead of `Actions::AddTodo`, which was pretty funny, but not what I was expecting. :-)

**Comment by iliabylich** [comment] 2015-12-30 21:16
Looks like it was fixed in https://github.com/opal/opal/pull/1259, could you check your code with the latest master?

**Comment by elia** [comment] 2015-12-30 22:29
I can confirm it's fixed on master.

@jgaskins let me know if you need a point release for the 0.9 series, as master is pointing towards 0.10 already.

**Closed by elia** 2015-12-30 22:29 UTC

**Comment by jgaskins** [comment] 2015-12-30 22:50
Oops, I thought I _was_ running against master. Turns out it was master for `opal-rails` not `opal`.
