### ISSUE TITLE
index is not defined with `with_index` method

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#781] opened 2015-03-29 10:09 UTC
Hello,

I have the following Ruby code:
```ruby
  def self.prepare_data(raw_data)
    labels = raw_data[0]
    raw_data.shift
    raw_data.map.with_index do |row, index|
      row.unshift "#{index}"
    end
    return raw_data, labels
  end
```

`raw_data` is an array (rows) of array (columns) obtained with `CSV.parse` method.
The JavaScript version with Opal 0.6.3:

```javascript
    $opal.defs(self, '$prepare_data', function(raw_data) {
      var $a, $b, TMP_1, self = this, labels = nil;

      labels = raw_data['$[]'](0);
      raw_data.$shift();
      ($a = ($b = raw_data.$map()).$with_index, $a._p = (TMP_1 = function(row, index){var self = TMP_1._s || this;
if (row == null) row = nil;if (index == null) index = nil;
      return row.$unshift("" + (index))}, TMP_1._s = self, TMP_1), $a).call($b);
      return [raw_data, labels];
    });
```

I can debug until `($a = ($b = raw_data.$map()).$with_index, $a._p = (TMP_1 = function(row, index){var self = TMP_1._s || this;` line is executed and I get the following error `index is not defined`.

The code is working fine in Ruby and I can't see what I am doing wrong... I saw a fix in Opal 0.7.0 about `Enumerator#with_index` maybe it's related ?

(I 've extracted only a portion of the code, if you need the complete file just ask me)

Thanks for your help.

**Comment by elia** [comment] 2015-03-29 10:13
You have a link to the fix at hand?

If it's really trivial I can backport it to 0.6 and release 0.6.4 (if @adambeynon agrees) otherwise I guess you'll have to workaround it with some external index var (btw I hate to suggest that :frog:).

**Comment by Mogztter** [comment] 2015-03-29 13:54
> You have a link to the fix at hand?

I found mention of the fix in the [CHANGELOG](https://github.com/opal/opal/blob/master/CHANGELOG.md#070-2015-02-01) but I think it's f151e851003bceec1f5c716923e5bb56dc67bcb0

> If it's really trivial I can backport it to 0.6 and release 0.6.4 (if @adambeynon agrees) 

That would be awesome. 
By the way I tried to build the `dist` for `v0.7.0` and `v0.7.1` to update the opal-cdn accordingly but I'm stuck with an error: https://github.com/opal/opal-cdn/issues/2#issuecomment-87388144

> otherwise I guess you'll have to workaround it with some external index var (btw I hate to suggest that :frog:).

That would be less awesome but let's see what @adambeynon decide :smile:

**Comment by elia** [comment] 2015-03-29 18:19
About the cdn issue I saw that, the problem is that minitest has become part of the stdlib but is intended as wip, but the dist task blindly tries to compile all files in the stdlib dir, see the solution that I'm going to post on the original issue.

**Comment by elia** [comment] 2015-05-10 21:00
Closing, since opal/opal-cdn#2 is solved I'm closing this, if it's absolutely necessary to have this in 0.6 my advice is to backport the code from 0.7 in something like `opal_ext.js.rb`.

**Closed by elia** 2015-05-10 21:00 UTC
