### ISSUE TITLE
Ruby error message not replicated when calling an unused argument

### ISSUE THREAD

**Issue by tansaku** [opal/opal#1287] opened 2016-01-14 12:52 UTC
Opal is awesome, however I notice that in some cases I don't get the Ruby error message I would expect, e.g. "wrong number of arguments"

In some cases I can ensure that we get the expected behaviour by setting arity_check_enabled to true, however I notice if I try and run something where the unused variable is actually referenced then even with arity_check_enabled I still get a JS error rather than the expected Ruby one, e.g. 

```ruby
def random_name(string)
  string
end

puts "Hello, #{random_name}"
```

gives 

```
TypeError: Cannot read property '$==' of undefined
``` 

in Ruby irb this code gives:

```
2.2.3 :007 > def random_name(string)
2.2.3 :008?>     string
2.2.3 :009?>   end
 => :random_name 
2.2.3 :010 > 
2.2.3 :011 >   puts "Hello, #{random_name}"
ArgumentError: wrong number of arguments (0 for 1)
```

is there any way to have Opal replicate the Ruby error message in this case?

**Comment by iliabylich** [comment] 2016-01-14 12:56
I can't reproduce your issue on the latest master:
``` sh
$ cat test.rb
def random_name(string)
  string
end

puts "Hello, #{random_name}"
$ opal -A test.rb
ArgumentError: [Object#random_name] wrong number of arguments(0 for 1)
```

(tested on 0.8.1 - getting the same error). Are you sure that arity checking was enabled?

**Comment by tansaku** [comment] 2016-01-14 13:10
thanks @iliabylich , we're on opal 7.2, and we're sort of stuck there because we're deploying with a middleman site that needs a different version of sprockets from opal :-( 

```
Bundler could not find compatible versions for gem "sprockets":
  In Gemfile:
    middleman (~> 3.3.12) ruby depends on
      middleman-sprockets (>= 3.1.2) ruby depends on
        sprockets-sass (~> 1.3.0) ruby depends on
          sprockets (~> 2.0) ruby

    opal (~> 0.8.1) ruby depends on
      sprockets (~> 3.1) ruby
```

I guess we need to upgrade middleman ... :-/

**Comment by elia** [comment] 2016-04-01 21:46
@tansaku closing this as we can't do much about it, except maybe but pointing out that opalrb.org successfully uses middleman with the latest opal: https://github.com/opal/opal.github.io/blob/source/Gemfile

**Closed by elia** 2016-04-01 21:46 UTC
