### ISSUE TITLE
proc and lambda difference

### ISSUE THREAD

**Issue by RohitRox** [opal/opal#260] opened 2013-05-14 07:44 UTC
``` ruby
  l = lambda { |first,last| puts "Fullname: #{first} #{last}"}
  l.call('roxx') #works
  # should give error because  a lambda should check the the number of arguments it     receives and return an ArgumentError if they do not match.
```

---

_next lines added by @elia_
- [x] arguments check
- [ ] return from lambda

**Comment by bwl21** [comment] 2016-03-27 17:48
The issue is somewhat old, but still existing and breaking gems

```ruby
def runwithlambda()
  puts "runwithlambda"
  ap1 = lambda{ |i| return " explicit return >2" if i > 2
    "implicit return #{i} " + ap1[i+1]
  }

  return ap1[0]
end


def runwithproc()
  puts "runwithproc"
  ap1 = proc{ |i|
    return " explicit return >2" if i > 2
    "implicit return #{i} " + ap1[i+1]
  }

  return ap1[0]
end

puts runwithproc()

puts runwithlambda()
````
Run with opal:
```
> opal vl.rb
runwithproc
 explicit return >2
runwithlambda
 explicit return >2
````

We see that in both cases return also returns from the containing method in both cases.
```
Runs with ruby 2.2.1:
ruby vl.rb
runwithproc
 explicit return >2
runwithlambda
implicit return 0 implicit return 1 implicit return 2  explicit return >2
````
We see that only runwithproc return also returns from the containing method in both cases.

Is there a chance to get this fixed (at least for explicit lambdas)?

Until it is fixed, it should be mentioned in the list of unsupported features.

**Comment by hmdne** [comment] 2021-07-05 20:10
This is fixed now:

```ruby
[user@localhost opal]# opal -A <<< 'l = lambda { |first,last| puts "Fullname: #{first} #{last}"}; l.call("roxx")'
ArgumentError: `block in <main>': wrong number of arguments (1 for 2)
[user@localhost opal]# opal -A <<< 'l = proc { |first,last| puts "Fullname: #{first} #{last}"}; l.call("roxx")'
Fullname: roxx 
[user@localhost opal]# 
```

(-A is arity check)

**Comment by hmdne** [comment] 2021-07-05 20:11
But the returns still don't work...

**Closed** 2021-08-31 17:32 UTC
Labels: bug, compiler, runtime, help wanted, v0.11, v1.1
