### ISSUE TITLE
Bug: If `$~` is evaluated/called then `$1`, `$2`... returns `nil`

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#2352] opened 2021-11-07 12:41 UTC
**Describe the bug**

Opal version: v1.3.1

**To Reproduce**

```rb
'a:b'.gsub(/([a-z]):([a-z])/) do
  p $~
  target, content = $1, $2
  p target
  p content
end
```

```
$ ruby -v test.rb      
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
#<MatchData "a:b" 1:"a" 2:"b">
"a"
"b"
```

```
$ opal -v test.rb
Opal v1.3.1
#<MatchData "a:b" 1:"a" 2:"b">
nil
nil
```

If you remove (or comment) the line `p $~` then it's working as expected:

```
$ opal -v test.rb
Opal v1.3.1
"a"
"b"
```

**Comment by hmdne** [comment] 2021-11-07 13:02
This bug is actually related to `p $~` being called. I assume it uses regexp somewhere.

**Comment by hmdne** [comment] 2021-11-07 13:05
The issue is here:

```
  def names
    source.scan(/\(?<(\w+)>/).map(&:first).uniq
  end

  def named_captures
    source.scan(/\(?<(\w+)>/)        # Scan for capture groups
          .map(&:first)              # Get the first regexp match (\w+)
          .each_with_index           # Add index to an iterator
          .group_by(&:first)         # Group by the capture group names
          .transform_values do |i|   # Convert hash values
            i.map { |j| j.last + 1 } # Drop the capture group names; increase i>
          end
  end
```

**Comment by hmdne** [comment] 2021-11-07 13:25
@Mogztter We will try to have v1.3.2 released on Wednesday with all the PRs marked as `stable-backport`.

**Comment by Mogztter** [comment] 2021-11-07 16:57
Awesome, thanks 🙌🏻

**Closed** 2021-11-10 08:56 UTC
Labels: bug
