### ISSUE TITLE
Opal with polymer-starter-kit : 'too much recursion' error

### ISSUE THREAD

**Issue by darkslategrey** [opal/opal#1065] opened 2015-08-17 20:15 UTC
polymer-starter-kit-1.0.3
current opalrb cdn version

When add opalrb to the polymer starter, the app kit cannot run because of this error : 
```javascript
too much recursion
for (var i in target) {
	
Polymer... return (line 2901, col 9)
```

**Comment by meh** [comment] 2015-08-17 20:27
That's not very helpful, is it the complete error? Can you get a stacktrace or give us line 2901?

**Comment by darkslategrey** [comment] 2015-08-17 21:12
Here is the stacktrace from bugzilla: 

```text
Polymer.StyleCache.prototype._objectsEqual()Polymer... return (line 2901)
target = []
source = []
Polymer.StyleCache.prototype.retrieve()Polymer... return (line 2890)
is = "iron-icon"
keyValues = []
keyStyles = [style]
._updateStyleProperties()Polymer... return (line 3001)
._beforeAttached()Polymer... return (line 2981)
.attachedCallback()Polymer...) { thi (line 85)
_attached()webcomp...lite.js (line 1790)
element = iron-icon
attached()webcomp...lite.js (line 1783)
element = iron-icon
added()webcomp...lite.js (line 1748)
node = iron-icon
isAttached = true
addedSubtree/<()webcomp...lite.js (line 1753)
e = iron-icon
forSubtree/<()webcomp...lite.js (line 1685)
e = iron-icon
findAllElements()webcomp...lite.js (line 1701)
node = a users
find = function(e)
data = undefined
findAllElements()webcomp...lite.js (line 1702)
node = div.selectable-content.style-scope.paper-menu
find = function(e)
data = undefined
findAllElements()webcomp...lite.js (line 1702)
node = paper-menu.list.x-scope.paper-menu-0
find = function(e)
data = undefined
findAllElements()webcomp...lite.js (line 1702)
node = paper-scroll-header-panel
find = function(e)
data = undefined
findAllElements()webcomp...lite.js (line 1702)
node = div#drawer.style-scope.paper-drawer-panel
find = function(e)
data = undefined
findAllElements()webcomp...lite.js (line 1702)
node = iron-selector.left-drawer.transition.style-scope.paper-drawer-panel
find = function(e)
data = undefined
findAllElements()webcomp...lite.js (line 1702)
node = paper-drawer-panel#paperDrawerPanel.x-scope.paper-drawer-panel-0
find = function(e)
data = undefined
forSubtree()webcomp...lite.js (line 1684)
node = paper-drawer-panel#paperDrawerPanel.x-scope.paper-drawer-panel-0
cb = function(e)
addedSubtree()webcomp...lite.js (line 1752)
node = paper-drawer-panel#paperDrawerPanel.x-scope.paper-drawer-panel-0
isAttached = true
addedNode()webcomp...lite.js (line 1741)
node = paper-drawer-panel#paperDrawerPanel.x-scope.paper-drawer-panel-0
isAttached = true
handler/</<()webcomp...lite.js (line 1859)
n = paper-drawer-panel#paperDrawerPanel.x-scope.paper-drawer-panel-0
handler/<()webcomp...lite.js (line 1855)
mx = MutationRecord { type="childList", target=body.fullbleed.layout.vertical, addedNodes=NodeList, more...}
handler()webcomp...lite.js (line 1853)
root = Document localhost:3000
mutations = [MutationRecord { type="childList", target=body.fullbleed.layout.vertical, addedNodes=NodeList, more...}]
```

And here the source code where the too much recursion occured

```javascript
_objectsEqual: function (target, source) {
    var t, s;
    for (var i in target) {  /// <== here is the 2901 line
	t = target[i], s = source[i];
	if (!(typeof t === 'object' && t ? this._objectsStrictlyEqual(t, s) : t === s)) {
	    return false;
	}
    }
    if (Array.isArray(target)) {
	return target.length === source.length;
    }
    return true;
},
```

**Comment by elia** [comment] 2015-08-17 21:27
@darkslategrey the problem is line 2901, using `for in` with arrays is bad practice in js for a number of reasons, it should be fixed in polymer-starter-kit

Here's the full explanation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in#Array_iteration_and_for...in

**Closed by elia** 2015-08-17 21:27 UTC
