### ISSUE TITLE
Issue with require, require_relative, require_tree ?

### ISSUE THREAD

**Issue by blocknotes** [opal/opal#2026] opened 2019-11-11 07:45 UTC
Hi :smiley: 
I did some experiments with opal 1.0 and I had some problems requiring other sources.
Some examples:

```rb
# foo.rb
puts 'foo'
```

```rb
# bar.rb
require 'foo'
puts 'bar'
```

Running it (using `opal bar.rb`) I get the error: `A file required by "bar.rb" wasn't found. (Opal::Builder::MissingRequire) can't find file: "foo"`
Same error with `require 'foo.rb'`.
The only working line is `require './foo.rb'`

---

Then I tried to use `require_relative`. In the above `bar.rb` file I replaced the require line with:
`require_relative './foo.rb'`
But I get always the same `MissingRequire` error

---

Last one: I tried to use `require_tree`. In the above `bar.rb` file I replaced the require line with:
`require_relative './lib'`. And I moved `foo.rb` in lib path.
When I run my code the `foo.rb` is not included.

I looked in the docs and the syntax seems right.

**Comment by sonota88** [comment] 2020-05-31 04:40
Want to try the `-I` option?

```
$ bundle exec opal -v
Opal v1.0.0

$ bundle exec opal --help | grep include
    -I, --include DIR                Append a load path (may be used more than once)

$ bundle exec opal -I. bar.rb
Failed to load WithCLexer, using pure Ruby lexer
foo
bar
```

**Comment by elia** [comment] 2020-06-09 22:17
Yeah, the problem is most probable the one highlighted by @sonota88, you can solve it either by using `-I` from the CLI or `Opal.append_path` when compiling from Ruby.

I'm closing this, feel free to ping me to get this re-opened if the above solutions do not work.

**Closed by elia** 2020-06-09 22:17 UTC
