### ISSUE TITLE
`bundle install` fails on master

### ISSUE THREAD

**Issue by Ajedi32** [opal/opal#1018] opened 2015-07-20 04:33 UTC
So I'm trying to get a basic development environment set up on my laptop, and ran into the following error while trying to run `bundle install`.

```text
$ bundle install
DL is deprecated, please use Fiddle
Updating git://github.com/ruby/mspec.git
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "rake":
  In snapshot (Gemfile.lock):
    rake (= 10.0.4)

  In Gemfile:
    rake (~> 10.3.2) x86-mingw32

    opal-minitest (>= 0) x86-mingw32 depends on
      rake (~> 10.3.2) x64-mingw32

    rake (>= 0) x86-mingw32

    rake (>= 0) x64-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Normally I'd resolve this with a `bundle update` as suggested in the error message, but that would change the dependencies in `Gemfile.lock`, and I'm not sure it's a good idea to do that without first understanding why I'm getting this error in the first place.

I'm running Windows 8.1 on a 64 bit machine, FYI.

**Comment by elia** [comment] 2015-07-20 05:39
Look more like an issue with bundler. I do bundle update regularly when developing gems, if something brakes it's a bug as people installing the gem for the first time will have similar similar results. 

Also be sure bundler is updated. 

Closing as not strictly related to Opal and because I don't think I can do much.

**Closed by elia** 2015-07-20 05:39 UTC

**Comment by vais** [comment] 2015-07-20 06:37
@Ajedi32 that's strange, considering that `Gemfile.lock` is **not** part of Opal repo at all. So, this `Gemfile.lock` may be there from you doing `bundle install` before.

Start from scratch - clone the repo, then do `bundle install`, and all shall be fine.

P.S. I just confirmed on my Windows XP VM, everything is a-ok:
```
C:\Documents and Settings\Administrator>ruby -v
ruby 2.0.0p247 (2013-06-27) [i386-mingw32]
C:\Documents and Settings\Administrator>cd Desktop

C:\Documents and Settings\Administrator\Desktop>git clone https://github.com/opal/opal.git
Cloning into 'opal'...
remote: Counting objects: 37090, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 37090 (delta 44), reused 1 (delta 1), pack-reused 36987
Receiving objects: 100% (37090/37090), 9.64 MiB | 222.00 KiB/s, done.
Resolving deltas: 100% (22449/22449), done.

C:\Documents and Settings\Administrator\Desktop>cd opal

C:\Documents and Settings\Administrator\Desktop\opal>bundle install
Fetching git://github.com/ruby/mspec.git
Fetching gem metadata from https://rubygems.org/...........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 10.4.2
Installing addressable 2.3.8
Using bundler 1.6.5
Using coderay 1.1.0
Installing diff-lcs 1.2.5
Installing multipart-post 2.0.0
Installing faraday 0.9.1
Installing ffi 1.9.10
Using formatador 0.2.5
Installing rb-fsevent 0.9.5
Installing rb-inotify 0.9.5
Installing listen 3.0.2
Using lumberjack 1.0.9
Installing nenv 0.2.0
Installing shellany 0.0.1
Installing notiffany 0.0.6
Using method_source 0.8.2
Installing slop 3.6.0
Using win32console 1.3.2
Installing pry 0.10.1
Using thor 0.19.1
Installing guard 2.12.8
Using hike 1.2.3
Using mspec 1.8.0 from git://github.com/ruby/mspec.git (at master)
Installing sawyer 0.5.5
Installing octokit 2.4.0
Installing sourcemap 0.1.1
Installing rack 1.6.4
Installing sprockets 3.2.0
Installing tilt 2.0.1
Using opal 0.8.0.rc2 from source at .
Installing opal-minitest 0.0.4
Installing racc 1.4.12
Installing rack-test 0.6.3
Installing rspec-core 2.99.2
Installing rspec-expectations 2.99.2
Installing rspec-mocks 2.99.4
Installing rspec 2.99.0
Installing terminal-notifier-guard 1.6.4
Installing yard 0.8.7.6
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

**Comment by Ajedi32** [comment] 2015-07-20 16:19
[Ah!](https://github.com/opal/opal/blob/master/.gitignore#L5) :flushed: Yeah, I was working from an old checkout of Opal. Didn't notice that `Gemfile.lock` wasn't actually in the repo. A `bundle update` should do the trick then...
