### ISSUE TITLE
nested blocks cause syntax err with break 

### ISSUE THREAD

**Issue by patrickkettner** [opal/opal#1598] opened 2016-12-02 03:28 UTC
given the following

```rb
[].each { |i|
  [].each {}
  break
}
``` 

Opal generates

```js
(function(Opal) {
  var $a, $b, TMP_1, self = Opal.top,
    $scope = Opal,
    nil = Opal.nil,
    $breaker = Opal.breaker,
    $slice = Opal.slice;

  Opal.add_stubs(['$require', '$each']);
  self.$require("opal");
  return ($a = ($b = []).$each, $a.$$p = (TMP_1 = function(i) {
    var self = TMP_1.$$s || this,
      $c, $d, TMP_2;
    if (i == null) i = nil;
    ($c = ($d = []).$each, $c.$$p = (TMP_2 = function() {
      var self = TMP_2.$$s || this;

      return nil
    }, TMP_2.$$s = self, TMP_2.$$arity = 0, TMP_2), $c).call($d);

    Opal.brk(nil, $brk);
  }, TMP_1.$$s = self, TMP_1.$$arity = 1, TMP_1), $a).call($b);
})(Opal);
```

notice that `$brk` is never defined, but referenced in the `Opal.brk` call

This only happens when you have a break _and_ a block inside of another block.

As a workaround, move the inner block to a separate method called inside of the containing block. 

```rb
[].each { |i|
  foo
  break
}

def foo
  [].each {}
end
```

**Comment by CicholGricenchos** [comment] 2017-05-22 04:27
I can't confirm this in master branch.

This bug is caused by https://github.com/opal/opal/blob/0-10-stable/lib/opal/compiler.rb#L302 where the inside `yield` writes nil to `@break_detected`, causing outer expr losts its break.

This patch can fix the bug in 0-10:
```ruby
def has_break?
  return @break_detected unless block_given?
  original_break_detected = @break_detected
  @break_detected = false
  result = yield
  detected = @break_detected
  @break_detected = original_break_detected
  detected
end
```

In master branch, `Opal::Rewriters::BreakFinder` is used to find breaks and it doesn't have this issue.

**Comment by elia** [comment] 2017-05-22 20:39
@patrickkettner I can confirm it's fixed on master, thanks to @CicholGricenchos for noticing!

---

```
⤑ opal _0.10.4_ -e "p([1,2,3].each { |i|                                       ~
    [4,5,6].each {|n| p n}
    break 123
  })"
/Users/elia/.rvm/gems/ruby-2.4.0/gems/opal-0.10.4/lib/opal/nodes/iter.rb:118: warning: constant ::Fixnum is deprecated
4
5
6
/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20170522-54286-hiqwxg:19546
    Opal.brk(123, $brk);}, TMP_1.$$s = self, TMP_1.$$arity = 1, TMP_1), $a).call($b))
                  ^

ReferenceError: $brk is not defined
    at TMP_1 (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20170522-54286-hiqwxg:19546:19)
    at Object.Opal.yield1 (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20170522-54286-hiqwxg:1198:14)
    at Array.$$each [as $each] (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20170522-54286-hiqwxg:11224:26)
    at /private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20170522-54286-hiqwxg:19546:77
    at Object.<anonymous> (/private/var/folders/w0/yjfqr9n94ld7ft4j3hlz_fsm0000gn/T/opal-nodejs-runner-20170522-54286-hiqwxg:19547:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
⤑ opal -ve "p([1,2,3].each { |i|                                               ~
    [4,5,6].each {|n| p n}
    break 123
  })"
Opal v0.11.0.rc1
4
5
6
123
⤑                            
```

**Closed by elia** 2017-05-22 20:39 UTC
Labels: bug, language
