### ISSUE TITLE
Bug: "gem install opal"; opal does not work, stack level too deep

### ISSUE THREAD

**Issue by rubyFeedback** [opal/opal#2229] opened 2021-06-05 08:00 UTC
When trying to run opal:

    opal

I get this error:

<internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:166:in `inspect': stack level too deep (SystemStackError)
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:166:in `inspect'
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:166:in `ensure in require'
        from <internal:/usr/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:167:in `require'
        from /usr/bin/opal:3:in `<top (required)>'
        from /usr/bin/opal:4:in `load'
        from /usr/bin/opal:4:in `<top (required)>'
        from /usr/bin/opal:4:in `load'
        from /usr/bin/opal:4:in `<top (required)>'
         ... 11900 levels...
        from /usr/bin/opal:4:in `load'
        from /usr/bin/opal:4:in `<top (required)>'
        from /usr/bin/opal:4:in `load'
        from /usr/bin/opal:4:in `<main>'

The content of my /usr/bin/opal is:

    #!/usr/bin/env ruby

    require 'bundler/setup'
    load "#{__dir__}/../bin/opal"

I did not do anything aside from the "gem install opal". I remember that
it used to work in the past. Has /usr/bin/opal changed? The load ""
part is quite strange. When a ruby gem is properly installed, this
bundler setup line should never be necessary. It seems to evaluate
to itself? I don't really use bundler myself, "gem install" always works
fine via .gemspec.

**Comment by hmdne** [comment] 2021-06-05 13:46
Similar to #2163.

This file is obviously wrong, because it tries to load itself ad infinitum.

My bin/opal looks like this:

```ruby
#!/usr/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'opal' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('opal', 'opal', version)
else
gem "opal", version
load Gem.bin_path("opal", "opal", version)
end
```

**Comment by hmdne** [comment] 2021-06-05 13:52
What's your Ruby distributor (as in: Linux distribution probably)? Are you sure your gem command is verbatim? What's an output of your `set | grep GEM` command and also what's the content of your `~/.gemrc` .

Can you reproduce this on a clean slate virtual machine or a docker/podman container (a Dockerfile could be an immense help in identifying and fixing this problem)?

**Comment by elia** [comment] 2022-03-11 09:24
Closing, @rubyFeedback feel free to reopen/ping if this is still an issue 👍

**Closed by elia** 2022-03-11 09:24 UTC
Labels: bug
