### ISSUE TITLE
Bug:  eval("<<~HEREDOC\nsquiggle heredoc is busted\nHEREDOC")

### ISSUE THREAD

**Issue by catmando** [opal/opal#2363] opened 2021-11-20 05:55 UTC
**Describe the bug**
on the client 

eval("<<~HEREDOC\nsquiggle heredoc is busted\nHEREDOC") 

Throws an error cause it trys to use string.slice!

Opal version: …

1.2

**To Reproduce**

go into yer browser and type:

Opal.Object.$new().$eval('<<~HEREDOC\nsquiggle heredoc is busted\nHEREDOC')

change squiggly to "-" and all is well

**Comment by hmdne** [comment] 2021-11-20 06:07
Duplicate of #2169

**Closed** 2021-12-20 10:16 UTC
Labels: bug
