### ISSUE TITLE
LoadError: cannot load such file -- opal

### ISSUE THREAD

**Issue by jeezs** [opal/opal#2032] opened 2019-12-04 07:46 UTC
Using the static version of opal 1.0.0  adding the following  ` <script src="opal.js" onload="Opal.require('opal')"></script> `
there's an "LoadError: cannot load such file -- opal"  error.

**Comment by Mogztter** [comment] 2019-12-04 16:39
I believe it's because opal is not defined as a module in `opal.js`:


```js
(function(Opal) {
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.const_get_qualified, $$ = Opal.const_get_relative, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$require']);
  
  self.$require("opal/base");
  self.$require("opal/mini");
  self.$require("corelib/kernel/format");
  self.$require("corelib/string/encoding");
  self.$require("corelib/math");
  self.$require("corelib/complex");
  self.$require("corelib/rational");
  self.$require("corelib/time");
  self.$require("corelib/struct");
  self.$require("corelib/io");
  self.$require("corelib/main");
  self.$require("corelib/dir");
  self.$require("corelib/file");
  self.$require("corelib/process");
  self.$require("corelib/random");
  self.$require("corelib/random/mersenne_twister.js");
  return self.$require("corelib/unsupported");
})(Opal);
```
https://github.com/opal/opal/blob/master/opal/opal.rb

So we should indeed remove the "onload" directive.
I think we should this issue to the https://github.com/opal/opal-cdn repository.

**Comment by elia** [comment] 2019-12-06 18:57
Closing this as a duplicate of https://github.com/opal/opal-cdn/issues/35, the problem is with the advertised code more than the `dist` task, although we should probably change things in future versions.

**Closed by elia** 2019-12-06 18:57 UTC
