### ISSUE TITLE
to_n isn't recursively called on arrays within a hash

### ISSUE THREAD

**Issue by ashes999** [opal/opal#1028] opened 2015-07-24 20:23 UTC
Originally found in #1024 . If you have a hash with arrays in it, `to_n` removes the Opal class instances from the hash, but not the arrays.

```
hash = {
  :images => ['one.png', 'bg.png'],
  :audio => ['point.ogg']
}
```

Calling `hash.to_n` gives me a hash with only two properties; but the two arrays each have Opal class instances in it.

This broke CraftyJS, because they iterated over this hash like so:

```
for (key in hash) {
  for (item in hash[key])
    if item.search('://') ... // error: method not found on OpalClass instance
  }
}
```

The solution was to use `hasOwnProperty`, which [they did in CraftyJS](https://github.com/craftyjs/Crafty/pull/943). However, `to_n` should still probably be fixed so that it recursively "native-ifies" arrays within the hash.

For reference, a quote from #1027:

> @elia:
> yes, actually there's already a place for that kind of docs at http://opalrb.org/docs/ under "API documentation". It's unfortunate that for some reason Native isn't covered and we need to fix that.
> As of the array to_n should call to_n on all its elements, if it doesn't let me know and we'll ask @meh to fix it :blush:

The easiest test, in my opinion, is to iterate using `fox item in hash[key]` and printing out the count. It should be 1-2 (the number of items in the array), not 300+.

I have codified my example [here](http://opalrb.org/try/?code:hash%20%3D%20%7B%0A%20%20%3Aimages%20%3D%3E%20%5B%27one.png%27%2C%20%27bg.png%27%5D%2C%0A%20%20%3Aaudio%20%3D%3E%20%5B%27point.ogg%27%5D%0A%7D.to_n%0A%0A%60for%20(key%20in%20hash)%20%7B%20for%20(item%20in%20hash%5Bkey%5D)%20%7B%20console.log(%22Item%3A%20%22%20%2B%20item)%3B%20%7D%20%7D%60) (on opalrb.org/try). See for yourself.

**Comment by Ajedi32** [comment] 2015-07-24 20:41
This is strange, because it seems `Hash#to_n` [actually does call `to_n` recursively](https://github.com/opal/opal/blob/master/stdlib/native.rb#L510-L512). Not quite sure what the problem is. Does Opal monkey patch the native array object or something? I don't really have Opal running on the PC I'm using right now so I can't easily debug and find out.

**Comment by ashes999** [comment] 2015-07-24 20:45
@Ajedi32 I've codified my example; [try it on opalrb.org](http://opalrb.org/try/?code:hash%20%3D%20%7B%0A%20%20%3Aimages%20%3D%3E%20%5B%27one.png%27%2C%20%27bg.png%27%5D%2C%0A%20%20%3Aaudio%20%3D%3E%20%5B%27point.ogg%27%5D%0A%7D.to_n%0A%0A%60for%20(key%20in%20hash)%20%7B%20for%20(item%20in%20hash%5Bkey%5D)%20%7B%20console.log(%22Item%3A%20%22%20%2B%20item)%3B%20%7D%20%7D%60)

**Comment by elia** [comment] 2015-07-24 20:54
Array is a bridged class (as String, Proc & others) which means that Opal methods are added to their prototype directly. 

Array will call to_n on its items but can't produce an array without the methods on its prototype which means that the fix to craftyjs is the only way (I know) to deal with this issue, and of course is also a good practice :)

**Comment by ashes999** [comment] 2015-07-24 20:55
Okay. I'll close this @elia .

**Comment by Ajedi32** [comment] 2015-07-24 23:41
[I've reduced the problem even further](http://opalrb.org/try/?code:%60%0Aarr%20%3D%20%5B%27one.png%27%2C%20%27bg.png%27%5D%0A%0Afor%20(item%20in%20arr)%20%7B%20console.log(%22Item%3A%20%22%20%2B%20item)%3B%20%7D%0A%60%0A).

IMO this is something that should be addressed. These properties shouldn't be enumerable. [Other properties on the array prototype aren't](http://opalrb.org/try/?code:%60%0Aarr%20%3D%20%5B%27one.png%27%2C%20%27bg.png%27%5D%0A%0Afor%20(item%20in%20arr)%20%7B%20console.log(%22Item%3A%20%22%20%2B%20item)%3B%20%7D%0A%60%0A#).

**Comment by ashes999** [comment] 2015-07-25 01:40
@Ajedi32 I don't see how that's the same problem. You're not calling `to_n` on your array.

**Comment by Ajedi32** [comment] 2015-07-25 02:18
@ashes999 That entire code block is in backticks; it's plain JavaScript. Opal is adding enumerable methods to the Array prototype, so all JavaScript Arrays are affected; not just the ones returned by `to_n`.

**Comment by elia** [comment] 2015-07-25 07:33
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

Object.prototype.defineProperty seems the only way to mark a property as non-enumerable. But we should talk about browser support and performance before going down this route.

**Comment by Ajedi32** [comment] 2015-07-25 17:42
> ## Browser compatibility
> Internet Explorer:	9 [1]
>
>[1] In Internet Explorer 8 only on DOM objects and with some non-standard behaviors.

Curse you Internet Explorer! :dizzy_face: 

I wonder if we really need to support the older IE versions though at this point... some of the recent statistics I'm seeing put IE6/7/8 at only 3.33% of the market, and that number can only go down from here. Idk though.

**Comment by ylluminate** [comment] 2015-07-25 20:50
Frankly I believe that with Windows 10 release, we're going to see a marked decline of this figure even further.  A lot of folks have already decided to move from Windows 7 and 8 to 10 and then of course it is going to be a pusher to get people to finally bump off of XP and Vista as well.  I am no longer convinced that it is worth supporting older IE versions and frankly have even started using things like https://browser-update.org in our projects to push people on ahead to safer and more sane options.

**Comment by meh** [comment] 2015-08-19 19:42
Closing this, discussion on whether to drop some ancient browser versions should happen in a separate issue.

**Closed** 2015-08-19 19:42 UTC
