### ISSUE TITLE
Native Bridging Rewrite

### ISSUE THREAD

**Issue by ylluminate** [opal/opal#667] opened 2014-12-12 05:00 UTC
Hey @meh, @ylluminarious was telling me about your work on the native bridging rewrite.  That looks really promising to clean up some of this stuff that has been done for inheritance.  How close are we to seeing that land?

**Comment by elia** [comment] 2015-05-05 08:40
Closing as duplicate of #631

**Closed by elia** 2015-05-05 08:40 UTC
