### ISSUE TITLE
Module#prepend is not implemented

### ISSUE THREAD

**Issue by h4ck3rm1k3** [opal/opal#1494] opened 2016-06-27 01:05 UTC
Don't know exactly what this is but people do it,
also where does the �� come from?

## input 
````
class Test123
  module Funky
    def foo()
    end
  end
  class<<self
    prepend Funky
  end
end
```
## GeneratedCode

````
/* Generated by Opal 0.11.0.dev */
(function(Opal) {
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $klass = Opal.klass, $module = Opal.module;

  Opal.add_stubs(['$prepend']);
  return (function($base, $super) {
    function $Test123(){};
    var self = $Test123 = $klass($base, $super, 'Test123', $Test123);

    var def = self.$$proto, $scope = self.$$scope;

    
    (function($base) {
      var $Funky, self = $Funky = $module($base, 'Funky');

      var def = self.$$proto, $scope = self.$$scope, TMP_1;

      Opal.defn(self, '$foo', TMP_1 = function ��foo() {
        var self = this;

        return nil
      }, TMP_1.$$arity = 0)
    })($scope.base);
    return (function(self) {
      var $scope = self.$$scope, def = self.$$proto;

      return self.$prepend($scope.get('Funky'))
    })(Opal.get_singleton_class(self));
  })($scope.base, null)
})(Opal);

````

## ERROR Message

```
/tmp/opal-nodejs-runner-20160626-15666-bvwlrn:4671
      throw exception;
      ^
prepend: undefined method `prepend' for #<Class:Test123>
    at Opal.defs.TMP_1 [as $new] (/tmp/opal-nodejs-runner-20160626-15666-bvwlrn:4886:15)
    at ��method_missing (/tmp/opal-nodejs-runner-20160626-15666-bvwlrn:3485:54)
    at method_missing_stub [as $prepend] (/tmp/opal-nodejs-runner-20160626-15666-bvwlrn:1079:35)
    at /tmp/opal-nodejs-runner-20160626-15666-bvwlrn:19360:19
    at /tmp/opal-nodejs-runner-20160626-15666-bvwlrn:19361:7
    at /tmp/opal-nodejs-runner-20160626-15666-bvwlrn:19362:5
    at Object.<anonymous> (/tmp/opal-nodejs-runner-20160626-15666-bvwlrn:19363:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

## Expected output

Ruby does compile the code, not sure what it does but it comes from real ruby code.

**Comment by iliabylich** [comment] 2016-06-27 10:11
@h4ck3rm1k3 Explanation is quite simple: `Module#prepend` is not implemented yet. :smile:

**Comment by elia** [comment] 2016-06-30 17:37
closing as duplicate of #796

**Closed by elia** 2016-06-30 17:37 UTC
