### ISSUE TITLE
bug: foo = ''; foo['bar'] ? true : false | is returning true.

### ISSUE THREAD

**Issue by cj** [opal/opal#700] opened 2015-02-17 20:53 UTC
Hi,

`foo = ''; foo['bar'] ? true : false` is returning true when it should be false. version 0.7.1.

@elia moved to opal (from https://github.com/opal/opal-jquery/issues/68).

**Comment by vais** [comment] 2015-02-18 06:33
In this case the problem is deeper: `foo['bar']` is returning a zero-length string whereas it should be returning `nil` according to Ruby. Since it is returning a string, the expression evaluates to true, as it should. 

In other words, the bug is not that the given expression evaluates to true, but that calling `[]` on a string with a parameter that is *not* a substring of that string, shall return `nil`.

How did that pass rubyspec?

**Comment by adambeynon** [comment] 2015-02-18 11:04
By the looks of it, we have filtered out the specs for `String#[]` accepting a string argument. We need to enable it, and then implement it. Surprised we haven't done it yet though.

**Comment by cj** [comment] 2015-02-18 22:17
@vais @adambeynon o wow...... any idea on when you'll be implementing it?

**Comment by adambeynon** [comment] 2015-02-18 22:19
@cj Will try and do it in the next couple of days. We can just use the ruby spec specs, and the actual implementation isn't too difficult really. Will post back when done.

**Comment by cj** [comment] 2015-02-18 22:20
@adambeynon thank you!

**Comment by vais** [comment] 2015-02-19 02:34
@adambeynon I would like to document the process of triaging a bug like this. What steps did you take to arrive at your conclusion? I.e. looked in this file, check that file, execute this command to run a specific test from the test suite, etc. This would help people like me who would love to contribute to the project but don't really know where to start.

**Comment by meh** [comment] 2015-02-19 17:03
@vais for what it's worth I'd go this way.

1. find the buggy method, in this case it's obviously `String#[]`
2. find the source file, in this case it's a corelib class and method, so it's in `opal/corelib`, the file is `string.rb`.
3. find the def for the buggy method
4. look at the code intensely preparing for the most awful experience because that method is awful for how many edge cases it has
5. change the code to do whatever it should be doing
6. `bundle exec opal-repl`
7. try to call the method to verify it's at least working
8. enable relevant specs
9. cry as some fail and you don't understand why
10. actually fix the method

**Comment by jaredcwhite** [comment] 2015-02-19 18:50
@meh That was funny. :)
@vais Thanks for asking that question. I too have been thinking of ways I could contribute to some of the libraries but it's a little daunting to jump in without knowing the ropes.

**Comment by vais** [comment] 2015-02-20 01:37
Thank you @meh, it is funny, but this actually helps a lot!

I do have more questions around points 8 and 9:

* find the relevant specs = ?
* enable the relevant specs = ?
* fail said specs (i.e. run them individually) = ?

**Comment by mieko** [comment] 2015-02-20 03:36
@vais, @jaredcwhite:

The list of test files that are ran are in `spec/rubyspecs`.  In this case, note that the following line is commented out:

```ruby
# corelib/core/string/element_reference_spec - fails to find a shared group - "String#[] with Regexp"
```

And later, the related:
```ruby
# corelib/core/string/slice_spec - fails to find a shared thing (same as element_reference_spec)
```

These are the files that contain the tests for `String#slice` and `String#[]` (in this case, deferred to `String#slice`)

This means that currently, these two methods aren't being tested, as the files aren't being loaded at all.  Once that's taken care of, there are corresponding filters in `spec/filters/bugs/string.rb`.  Currently, we expect these to fail (which leads me to believe the above specs used to be in the active set):

```ruby
  fails "String#[] with String returns other_str if it occurs in self"
  fails "String#[] with String returns nil if there is no match"
```

Also, the related:
```ruby
  fails "String#slice with String returns other_str if it occurs in self"
  fails "String#slice with String returns nil if there is no match"
```

If you remove these `fail`s, the test suite will fail as normal when ran.  Then it's down to fixing the implementation in `string.rb`.

I've been out of the testing loop for a bit, so I trust I'll be corrected if I've misstated anything. 

(/cc @meh @elia @adambeynon )

**Comment by vais** [comment] 2015-02-20 05:14
Awesome, thanks @mieko!

**Comment by meh** [comment] 2015-02-20 16:23
@mieko that is correct.

@vais the only thing to add is that if you enable some specs and there are some failures that you can't figure out how to fix or are impossible to support, you should add them to the proper filters.

`spec/filters/unsupported/<proper file>` in the case of something that cannot be supported at all in Opal, if you look at the file names in those files you should be able to figure out what goes where.

`spec/filters/bugs/<proper file>` in case it's a bug or something you haven't implemented yet from the spec.

**Comment by vais** [comment] 2015-02-21 02:16
@meh makes sense, thank you. @adambeynon unless you are already working on it, please let me know, and I'll take a shot at fixing this issue with `String#slice`.

**Comment by vais** [comment] 2015-02-23 01:20
@meh, @jaredcwhite, @mieko: just wanted to say thanks for your guidance and support getting me up to speed on contributing to opal. This issue with `String#[]` [is fixed now](https://github.com/opal/opal/pull/701).

**Closed** 2015-02-24 17:27 UTC
