### ISSUE TITLE
`expr or next` not supported

### ISSUE THREAD

**Issue by dan42** [opal/opal#2091] opened 2020-04-09 23:03 UTC
The following code:
```
4.times do
  2 or next
end
```
results in a javascript syntax error:
```
Uncaught SyntaxError: Unexpected token 'return'
```

**Comment by elia** [comment] 2020-05-28 08:09
This is a duplicate of #810, I've added it to the v1.1 milestone, since it came up more frequently lately.

**Closed** 2021-07-07 01:18 UTC
